from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
GENERATED_SRC = ROOT / "app" / "generated" / "openapi" / "src"


SECURITY_API = """# coding: utf-8

# Generated by OpenAPI Generator and patched by scripts/postprocess_generated_openapi.py.
from app.generated_security import get_token_bearerAuth

"""

IMPL_SHIM = """# coding: utf-8

# Generated integration shim. Real implementation lives in app.openapi_impl.
from app.openapi_impl import AuthApiImpl, OrdersApiImpl, ProductsApiImpl, PromoCodesApiImpl  # noqa: F401

"""


def main() -> None:
    if not GENERATED_SRC.exists():
        raise SystemExit("Generated OpenAPI server is missing. Run `make generate` first.")

    security_path = GENERATED_SRC / "generated_server" / "security_api.py"
    impl_dir = GENERATED_SRC / "openapi_server" / "impl"
    impl_dir.mkdir(parents=True, exist_ok=True)

    security_path.write_text(SECURITY_API)
    (impl_dir / "marketplace_impl.py").write_text(IMPL_SHIM)
    for api_file in (GENERATED_SRC / "generated_server" / "apis").glob("*_api.py"):
        text = api_file.read_text()
        text = text.replace("strict=True, ", "")
        text = text.replace(", strict=True", "")
        api_file.write_text(text)
    print("Patched generated OpenAPI server")


if __name__ == "__main__":
    main()
